CREATE TABLE users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
    username varchar(45) NOT NULL,
    password varchar(64) NOT NULL,
    role varchar(45) NOT NULL,
    enabled bool DEFAULT NULL
--     primary key (user_id)
    );

INSERT INTO users ( username, password, role, enabled)
    VALUES ( 'user', '$2a$10$XptfskLsT1l/bRTLRiiCgejHqOpgXFreUnNUa35gJdCr2v2QbVFzu','ROLE_USER',1),
           ( 'admin', '$2a$10$zxvEq8XzYEYtNjbkRsJEbukHeRx3XS6MDXHMu8cNuNsRfZJWwswDy','ROLE_ADMIN',1);